[workspace]
name = "toxoid_app"
members = [      
     "crates/toxoid_cli",
     "crates/toxoid_runtime",
     "crates/toxoid_guest",
     "crates/toxoid_api", 
     "crates/toxoid_bootstrap",
     "crates/toxoid_sokol",
     "app/host", 
     "app/guest",
]
exclude = []
