[package]
name = "toxoid_host"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
toxoid_wasm_runtime = { path = "../toxoid_wasm_runtime" }