[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
toxoid_host = { path = "../../crates/toxoid_host", optional = true }
guest = { path = "../guest", optional = true }

[features]
default = ["wasm-linking"]
wasm-linking = ["toxoid_host"]
static-linking = ["guest"]