[package]
name = "toxoid_wasm_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
# wasmtime = "24.0.0"
# wasmtime-wasi = "24.0.0"
wasm_component_layer = "0.1.18"
wasmi_runtime_layer = "0.36.0"
